runtime: nodejs16

env_variables:
  NODE_ENV: production

  INSTANCE_UNIX_SOCKET: /cloudsql/protekzi360-backend:asia-southeast2:protekzi-db
  
  
  DB_TYPE: postgres
  MY_DB_USER: postgres
  MY_DB_PASSWORD: Susanto1234!
  MY_DATABASE: postgres

  MIDTRANS_IS_PRODUCTION: true
  MIDTRANS_SERVER_KEY: Mid-server-MDR6GmYh7t1j0rq5WeeA16KN
  MIDTRANS_CLIENT_KEY: Mid-client-8dEt_cUYUQxhuBDv