steps:
- name: 'gcr.io/cloud-builders/npm'
  dir: 'protekzi360-rest-api'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  dir: 'protekzi360-rest-api'
  args: ['run', 'build']
- name: "gcr.io/cloud-builders/gcloud"
  dir: 'protekzi360-rest-api'
  args: ["app", "deploy"]
options:
  logging: CLOUD_LOGGING_ONLY
timeout: "1600s"